// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/engagement" | "/admin/events" | "/admin/posts" | "/admin/posts/[utmContent]" | "/admin/retailers" | "/admin/timeseries" | "/folders" | "/folders/[retailer]" | "/folders/[retailer]/p/[page]" | "/nl-grensstreek" | "/nl-grensstreek/[retailer]" | "/over-ons" | "/veelgestelde-vragen"
type AppRouteHandlerRoutes = "/admin/export/events" | "/ads.txt" | "/api/attribution" | "/api/engagement" | "/out/[retailer]"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = "/favicon.ico"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/engagement": {}
  "/admin/events": {}
  "/admin/export/events": {}
  "/admin/posts": {}
  "/admin/posts/[utmContent]": { "utmContent": string; }
  "/admin/retailers": {}
  "/admin/timeseries": {}
  "/ads.txt": {}
  "/api/attribution": {}
  "/api/engagement": {}
  "/favicon.ico": {}
  "/folders": {}
  "/folders/[retailer]": { "retailer": string; }
  "/folders/[retailer]/p/[page]": { "retailer": string; "page": string; }
  "/nl-grensstreek": {}
  "/nl-grensstreek/[retailer]": { "retailer": string; }
  "/out/[retailer]": { "retailer": string; }
  "/over-ons": {}
  "/veelgestelde-vragen": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
