// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/admin/engagement/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/engagement">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/engagement/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/events">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/posts/[utmContent]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/posts/[utmContent]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/posts/[utmContent]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/posts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/posts">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/posts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/retailers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/retailers">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/retailers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/timeseries/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/timeseries">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/timeseries/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/folders/[retailer]/p/[page]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/folders/[retailer]/p/[page]">> = Specific
  const handler = {} as typeof import("../../../src/app/folders/[retailer]/p/[page]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/folders/[retailer]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/folders/[retailer]">> = Specific
  const handler = {} as typeof import("../../../src/app/folders/[retailer]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/folders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/folders">> = Specific
  const handler = {} as typeof import("../../../src/app/folders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/nl-grensstreek/[retailer]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/nl-grensstreek/[retailer]">> = Specific
  const handler = {} as typeof import("../../../src/app/nl-grensstreek/[retailer]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/nl-grensstreek/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/nl-grensstreek">> = Specific
  const handler = {} as typeof import("../../../src/app/nl-grensstreek/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/over-ons/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/over-ons">> = Specific
  const handler = {} as typeof import("../../../src/app/over-ons/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/veelgestelde-vragen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/veelgestelde-vragen">> = Specific
  const handler = {} as typeof import("../../../src/app/veelgestelde-vragen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/export/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/admin/export/events">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/export/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/ads.txt/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/ads.txt">> = Specific
  const handler = {} as typeof import("../../../src/app/ads.txt/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/attribution/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/attribution">> = Specific
  const handler = {} as typeof import("../../../src/app/api/attribution/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/engagement/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/engagement">> = Specific
  const handler = {} as typeof import("../../../src/app/api/engagement/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/out/[retailer]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/out/[retailer]">> = Specific
  const handler = {} as typeof import("../../../src/app/out/[retailer]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
